BEGIN;
DROP VIEW article_public_noconcat_view;
DROP VIEW article_public_view;
DROP VIEW article_private_view;
DROP VIEW article_home_view;
DROP VIEW player_view;
DROP VIEW player_home_view;
DROP VIEW get_user_view;
DROP VIEW calendar_home_view;
DROP VIEW calendar_view;
COMMIT;
