@endpoint = http://localhost:{{$dotenv PORT}}/api

## Récupérer tous les articles

GET {{ endpoint }}/articles

### Récupérer les 3 derniers articles

GET {{ endpoint }}/articles?home=true

### création d'un article

POST {{ endpoint }}/articles/
Content-Type: application/json

{
  "slug": "nouvel-article",
  "title": "mon nouvel article",
  "content": "Ceci est le contenu de mon nouvel article",
  "author": "jack"

}

### Récupérer un article

GET {{ endpoint }}/articles/nouvel-article


### Modification d'un article

PATCH {{endpoint}}/articles/nouvel-article
Content-Type: application/json

{
  "slug": "ca-trop-marche-bien",
  "title": "Voyons si ça marche"
}

### Suppression d'un article
DELETE {{endpoint}}/articles/nouvel-article
