@endpoint = http://localhost:{{$dotenv PORT}}/api

### Récupérer tous les évents/calendrier/match
GET {{ endpoint }}/calendrier

### Récupérer 1 match à venir et 1 passé pour la homepage
GET {{ endpoint }}/calendrier?home=true

### Récupérer un évent

GET  {{ endpoint }}/calendrier/Event 1

### Création d'un évent

POST {{ endpoint }}/calendrier/
Content-Type: application/json

{
  "event_name": "tournoi world",
  "event_date": "2023-06-10 18:00:00",
  "adversary_name": "Team D",
  "adversary_name_short": "D"
}

### Modification d'un évent
PATCH {{ endpoint }}/calendrier/Event 1
Content-Type: application/json

{
  "event_name": "event team wolrd",
}

### Suppression d'un évent

DELETE {{ endpoint }}/calendrier/Event 1
