@endpoint = http://localhost:{{$dotenv PORT}}/api

### Envoyer un formulaire de recrutement
POST {{endpoint}}/recrutement/
{
  "username": "slayer",
  "email": "slayer@mail.com",
  "first_name":"robert",
  "last_name":"slayer",
  "external_link": "external_link_url",
  "message":"accepter ma demande je suis chaud"
}
